### ISSUE TITLE
Configuration for additional columns on dashboard

### ISSUE THREAD

**Issue by rcubed3r** [fluidd-core/fluidd#499] opened 2022-01-30 19:31 UTC
### Is your feature request related to a problem? Please describe

not a problem, just a request:
Like may others, I have a wide screen monitor. My dashboard layout has almost as much unused as used space to the left and right of the current two column setup. I would like to have the option to add columns in the dashboard layout.

### Describe the solution you'd like

I would like to see a configuration in the dashboard layout to add columns over the set two as it is now. The choice to have three columns would be great, and four may be even better.

**Comment by StuSerious** [comment] 2022-01-30 20:13
Hey there @rcubed3r, thanks for bringing this up! 
Your issue is a duplicate of #189, let's use that for discussion about the topic.

~S

**Closed by StuSerious** 2022-01-30 20:13 UTC
Labels: GH - Duplicate, !! - Invalid, UI - QoL
