### ISSUE TITLE
[1.16.2] Power Button from Moonraker out of sync

### ISSUE THREAD

**Issue by multiholle** [fluidd-core/fluidd#398] opened 2021-09-01 06:21 UTC
## Affected Version(s):
(The versions of fluidd this issue occurs on.)
- klipper version: 0.9.1-763-g3a497d04
- moonraker version: 0.7.1-42-g81176a6
- fluidd version: 1.16.2

## Reproduction Steps:
- setup a smart outlet power switch for the printer in moonraker
- configure klipper to switch off power when idle
- wait for idle timeout and printer shutdown

printer.cfg
```
[idle_timeout]
timeout: 300
gcode:
  M84
  TURN_OFF_HEATERS
  UPDATE_DELAYED_GCODE ID=delayed_printer_off DURATION=60

[delayed_gcode delayed_printer_off]
initial_duration: 0.
gcode:
  {% if printer.idle_timeout.state == "Idle" %}
    POWER_OFF_PRINTER
  {% endif %}
```
moonraker.conf
```
[power homeassistant_switch]
type: homeassistant
address: 192.168.178.90
port: 8123
device: switch.bed_desk_docking_station
token: topsecrettoken
domain: switch
restart_klipper_when_powered: True
restart_delay: 5
```

## Actual Results:
The power menu in fluidd (top right corner) will show the printer as "on" but the printer is actually turned off.

![image](https://user-images.githubusercontent.com/5654539/131624958-90aa294d-e381-4b29-b918-0471a3542d3f.png)

## Expected Results:
The power menu in fluidd (top right corner) will show the printer as "off".

**Comment by vajonam** [comment] 2021-11-13 17:15
yeah not sure whats going on here.. but double clicking seems to get things back in sync.. is the intended behaviour?

**Comment by ForsakenHarmony** [comment] 2021-11-15 12:06
I'm assuming reloading the page doesn't fix it?

**Comment by multiholle** [comment] 2021-11-15 12:11
Reloading the page doesn't help

**Comment by vajonam** [comment] 2021-11-15 12:17
Here is gif, the screen on the right is homeassistant that accurately reflects the state of the button. 

The first click doesn't see to send any requests. I can confrim that moonraker side is good because when I call the GCODE that does the power off/on. it works the very first time. Idle timeout for example works fine. 

![Peek 2021-11-15 07-14](https://user-images.githubusercontent.com/152501/141780577-f12a80b2-c6e2-42fd-90ac-0e7f73713f77.gif)

**Comment by vajonam** [comment] 2021-11-15 12:35
Both Mainsail and Fluidd have this issue, which made me thing it was moonraker thing, the code in there looks like it has all the bits implemented to query the state of the switch using the `/states/` API in homeassistant.

**Comment by ForsakenHarmony** [comment] 2021-11-15 13:02
Can you try going to `{moonraker_url}/machine/device_power/devices` and see which status is shown there?

**Comment by vajonam** [comment] 2021-11-15 13:07
Hmm. Your right.

```
{"result": {"devices": [{"device": "Ender3", "status": "off", "locked_while_printing": false, "type": "homeassistant"}]}}
```

This while the printer is connected and is on. Will open bug in moonraker.

**Comment by ForsakenHarmony** [comment] 2021-11-15 13:13
I'll close this, as the issue should be fixed when moonraker fixes it on their side

**Closed by ForsakenHarmony** 2021-11-15 13:13 UTC
Labels: GH - Bug, GH - Upstream First

**Comment by vajonam** [comment] 2021-11-15 13:52
I have found a provided a fix the code but issue was the return status needed a sleep for to give time for home assistant to return the correct state.

**Comment by vajonam** [comment] 2021-11-15 17:14
This fixed as per.
https://github.com/Arksine/moonraker/issues/273
