### ISSUE TITLE
Klipper and moonraker invalid, unable to recover!

### ISSUE THREAD

**Issue by hamed1998googoogaga** [fluidd-core/fluidd#697] opened 2022-05-26 22:02 UTC
### Browser

Chrome

### Device

Laptop

### Operating System

Windows

### What happened

I tried to print on a Raspberry Pi 3 Model B Rev 1.2 but could not because the Z was triggered, calibration had failed

After looking around I saw that both klipper and moonraker are "invalid" in the settings page and when I pressed recover it failed to do so.

The OS packages are also needing updates, but when I pressed those it failed aswell
![Updates Page](https://user-images.githubusercontent.com/106352909/170586847-c9c05385-b873-4356-94e4-6ee647e0f695.png)
.
![Klipper Invalid](https://user-images.githubusercontent.com/106352909/170586846-9295ce61-ef37-4799-b5c5-aa4e15708e94.png)

That last pic is me trying to recover klipper, moonraker is roughly the same, here is what happens when I try to update OS packages:
![Uploading OS update.png…]()

### What did you expect to happen

I expected fluidd to recover both klipper and moonraker, and update the OS packages, but nothing happened

### How to reproduce

Honestly I have no idea, Im very new to 3d printing and kinda just opened up the settings page to see this

### Additional information

Im not sure how to edit any proxy or code or anything, I tried looking around the gcode file are but Im stumped as to what Im looking at. Sorry in advance for my incompetence!

**Comment by pedrolamas** [comment] 2022-05-26 22:26
Hi @hamed1998googoogaga this means your Raspberry Pi can't access GitHub, so this is either a network issue or GitHub was down when it tried to access it.

I would recommend rebooting the Pi and trying again at a later time.

**Comment by hamed1998googoogaga** [comment] 2022-05-26 22:39
Ok I will try this tomorrow then and will let you know!

**Comment by hamed1998googoogaga** [comment] 2022-05-27 14:53
@pedrolamas Is there anyway to know when GitHub is down? I tried again today and still the same issues, my network seems to work fine.

Thanks!

**Comment by hamed1998googoogaga** [comment] 2022-05-27 15:56
^^^^Nevermind, I think I found out where to put the code, but I just need to actually connect the ssh to the pi, it is telling me that the host does not exist for some reason, Ill try to figure out why and get back to you

**Comment by hamed1998googoogaga** [comment] 2022-05-27 18:57
Hey @pedrolamas here is what happens when I insert that code into there
![Curl](https://user-images.githubusercontent.com/106352909/170773675-289f2146-2bf3-451e-89a9-6360d4782126.png)

**Comment by pedrolamas** [comment] 2022-05-27 19:21
That confirms that you do have a network issue as you can't reach github.com

You can also try `curl https://1.1.1.1`, if this works then the problem is most likely a DNS server issue.

Not much I can say besides telling you to check your firewall and DNS server...

**Comment by hamed1998googoogaga** [comment] 2022-05-30 16:11
Thanks for everything, I think you are right, it may be a network error, since I dont have a DNS server and I tried with my firewall turned off.

**Comment by pedrolamas** [comment] 2022-06-03 08:16
@hamed1998googoogaga, given this, are you ok for us to close this issue?

**Comment by hamed1998googoogaga** [comment] 2022-06-03 18:47
@pedrolamas yeah for sure

**Closed** 2022-06-03 18:57 UTC
Labels: ?? - Help Wanted
