### ISSUE TITLE
Download input shaper CSV to PC

### ISSUE THREAD

**Issue by Ltek** [fluidd-core/fluidd#1300] opened 2024-01-06 16:45 UTC
### Is your feature request related to a problem? Please describe

A lot of people now use Input Shaping. I'm sure some, including myself, like to download the CSVs and graph the output to compare how they have changed... especially when changing the environment (different table, moving spool holder, etc). Since Fluidd / Moonraker have access to the TMP folder, having a 1-button "Download CSVs from TMP folder" would be really helpful vs the multi-step SSH needed today.

### Describe the solution you'd like

1-button "Download CSVs from TMP folder" would be really helpful vs the multi-step SSH needed today.

### Describe alternatives you've considered

multi-step, manual SSH login and download

**Comment by pedrolamas** [comment] 2024-01-08 09:17
Duplicate of #1236

**Closed by pedrolamas** 2024-01-08 09:17 UTC
Labels: FR - Enhancement
