### ISSUE TITLE
Login in PC version has invisible symbol

### ISSUE THREAD

**Issue by SlimRG** [fluidd-core/fluidd#1421] opened 2024-04-23 18:29 UTC
### Fluidd Version

v1.29.1-fef6e12

### Browser

Chrome

### Device

Desktop PC, Mobile device (Phone, Tablet or similar)

### Operating System

Linux, Android

### What happened

When I create account on PC - I can join on PC
But when I connect local mobile and see invisible on PC symblol.

### What did you expect to happen

![image](https://github.com/fluidd-core/fluidd/assets/39348033/fb0faff2-26b7-46ff-bd52-b72f36324798)
And also, when I create account on mobile without this symbol - I can't connect by PC

### How to reproduce

Try to create and login by mobile and by pc without localhost

**Comment by SlimRG** [comment] 2024-04-23 19:22
From PC:
![image](https://github.com/fluidd-core/fluidd/assets/39348033/f3a39941-73f1-4615-8a22-b871a435962c)
From Android:
![image](https://github.com/fluidd-core/fluidd/assets/39348033/b837d15a-0d6a-4889-8fb6-a3ecd9ca589a)

**Comment by SlimRG** [comment] 2024-04-23 19:24
Upper login was created by phone, another - by PC with MS Edge

**Comment by pedrolamas** [comment] 2024-04-23 21:48
I am unsure of what has happened here... while it looks like you have 2 accounts with the same username, that is not the case as Moonraker would not allow duplicate accounts.

I am unsure of what this user character is, but my advice would be to remove the account and create it again.

**Comment by SlimRG** [comment] 2024-04-23 23:23
I made two accounts to login by phone and by PC

**Comment by SlimRG** [comment] 2024-04-23 23:27
For PC I made on PC and didn't see any invisible symbols.
But when I tried to connect by phone - I can't login with my login (SlimRG)
 So, I created second account through trusted user by phone with no invisible symbols.
 It's not a big problem to have two accounts (for PC and Phone)
 But, it's a bug, that you can reproduse.
 Oh, I forgot to say, PC on Linux (KDE Neon)

**Comment by SlimRG** [comment] 2024-04-24 00:56
As I think, you can trim login string and convert to a-Z0-9@. format

**Comment by SlimRG** [comment] 2024-04-24 01:06
I reinstall fluidd - the same problem

**Comment by pedrolamas** [comment] 2024-04-25 08:54
I have been unable to reproduce this issue with either my Windows PC running MS Edge, or on my Android phone also running MS Edge...

The only reason I see for this thing to happen would be if some browser extension is doing something to change the content of the data submitted!

Can I ask that you access `http://<moonraker-host>:715/access/users/list` and paste the response here?

**Comment by SlimRG** [comment] 2024-04-29 01:20
`{"result": {"users": [{"username": "SlimRG", "source": "moonraker", "created_on": 1713889753.240955}, {"username": "SlimRG\u007f", "source": "moonraker", "created_on": 1713896388.1075256}, {"username": "Test", "source": "moonraker", "created_on": 1714075482.5925968}]}}`

**Comment by SlimRG** [comment] 2024-04-29 01:25
> I have been unable to reproduce this issue with either my Windows PC running MS Edge, or on my Android phone also running MS Edge...
> 
> The only reason I see for this thing to happen would be if some browser extension is doing something to change the content of the data submitted!
> 
> Can I ask that you access `http://<moonraker-host>:715/access/users/list` and paste the response here?

I have extensions LastPass and AdGuard. But on other sites I had no problems with invisible symbol in login. Hmmm...

**Comment by pedrolamas** [comment] 2024-04-29 16:22
The `\u007f` character above is the `Delete` control character... not sure what is going on here, but the browser seems to have entered that in one of the usernames!

**Comment by pedrolamas** [comment] 2024-05-06 17:25
I haven't been able to reproduce this issue. I have only tested in Windows, but my gut feeling is that KDE input is somehow at play here as the `\u007f` character is the `Delete` control character - which should not feature on the input.

Nevertheless, I don't think this is a Fluidd issue and will now close this ticket, but keep an eye on for any other user having similar issues.

**Closed by pedrolamas** 2024-05-06 17:25 UTC
Labels: GH - Bug, GH - Evaluation Needed
