### ISSUE TITLE
 'repo: cadriel/fluidd' does not match detected repo 'fluidd-core/fluidd', falling back to detected version.

### ISSUE THREAD

**Issue by buikpijn** [fluidd-core/fluidd#1274] opened 2023-12-13 11:10 UTC
### Fluidd Version

1.26.3

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

Updating Fluidd through the default Fluidd envorinment, threw an error 'Value at option 'repo: cadriel/fluidd' does not match detected repo 'fluidd-core/fluidd', falling back to detected version.'

### What did you expect to happen

Just update without an error

### How to reproduce

Fluidd is no longer able to update automatically

**Comment by pedrolamas** [comment] 2023-12-13 11:13
Duplicate of #1238

**Closed by pedrolamas** 2023-12-13 11:13 UTC
Labels: GH - Bug, GH - Evaluation Needed
