### ISSUE TITLE
Extruder TMC2240 temperature covers the hotend temperature

### ISSUE THREAD

**Issue by Bixan** [fluidd-core/fluidd#1170] opened 2023-09-09 04:13 UTC
### Fluidd Version

v1.25.2-e06c7ad

### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

When the extruder uses TMC2240, the hotend temperature is covered by the drive temperature. You can't see the hotend temperature in the temperature curve
![OB1~K0~I`4 WB6XEQ}_%X43](https://github.com/fluidd-core/fluidd/assets/30937450/3b0929f6-5a8c-4c5a-aed5-3482a2c51fba)

![DAEWYJD290{8613`C1C1LXK](https://github.com/fluidd-core/fluidd/assets/30937450/099d9e03-298d-46ad-bd58-3b2d0336a088)

### What did you expect to happen

The drive temperature and hot end temperature curves are displayed separately

### How to reproduce

The extruder is driven by TMC2240

**Comment by pedrolamas** [comment] 2023-09-09 08:22
Thank you for reporting this @Bixan

I believe this issue is a duplicate of #1166 which has already been fixed for the next release.

**Closed** 2023-09-09 08:22 UTC
Labels: GH - Bug, GH - Duplicate
