### ISSUE TITLE
Fluidd update problem?

### ISSUE THREAD

**Issue by markwinger** [fluidd-core/fluidd#1298] opened 2024-01-01 17:31 UTC
### Fluidd Version

1.27.1

### Browser

Firefox

### Device

Desktop PC

### Operating System

Windows

### What happened

I updated my setup by clicking on the notification icon.  I updated all components, klipper, moonraker, fluidd, mobile-companion and os.  After that I show this with fluidd:
Value at option 'repo: cadriel/fluidd' does not match detected repo 'fluidd-core/fluidd', falling back to detected version. 
This happened a few updates ago, and still persists.  Is this a problem?  Ho do I resolve it?

### What did you expect to happen

I have been running this setup for years now and update often, and never seen a warning like this before.

### How to reproduce

Just click on update fluidd.

**Comment by pedrolamas** [comment] 2024-01-01 18:57
Duplicate of #1238

**Closed** 2024-01-01 18:58 UTC
Labels: GH - Duplicate
