### ISSUE TITLE
G code preview with large number of null layers

### ISSUE THREAD

**Issue by yasaslive** [fluidd-core/fluidd#684] opened 2022-05-18 19:51 UTC
### Browser

Chrome

### Device

Desktop PC

### Operating System

Windows

### What happened

- After updating to new fluidd G code previewer shows large number of null layers. Only last layers have the paths. 

### What did you expect to happen

Shows correct layers and layer path

### How to reproduce

Update to latest fluidd
![Screenshot 2022-05-19 012017](https://user-images.githubusercontent.com/42059631/169144135-d964d46b-75e6-4675-af0c-3d75d58e57d2.png)
![Screenshot 2022-05-19 012044](https://user-images.githubusercontent.com/42059631/169144142-550c4eb5-a8c5-4e80-a4e5-1d22ffa4aad5.png)

**Comment by pedrolamas** [comment] 2022-05-18 19:53
@yasaslive thanks you for submitting the bug report.

Can I ask that you supply a sample g-code file so we can check? Thank you!

**Comment by yasaslive** [comment] 2022-05-18 19:57
This is one of my gcode that generated couple minutes ago with PrusaSlicer 2.4.2. 
Infill: 40%
Layer height: .1mm
Speed: 100mm/s
Material: ABS

[money_cat.txt](https://github.com/fluidd-core/fluidd/files/8720452/money_cat.txt)

**Comment by pedrolamas** [comment] 2022-05-18 20:21
Duplicate of #674

Good news: this was fixed by #679 yesterday and the fix has already been merged to the `develop` branch!

Here's a screen-capture of the file you provided showing it works on the latest `develop`:

![Animation](https://user-images.githubusercontent.com/85504/169148700-be67fb7a-bdfb-45bd-add5-d0bd16069ac1.gif)

You can either check the `develop` branch or way for 1.18.1 release that should be available soon!

**Closed by pedrolamas** 2022-05-18 20:21 UTC
Labels: GH - Bug, GH - Evaluation Needed

**Comment by pedrolamas** [comment] 2022-05-18 20:22
Duplicate of #674
