### ISSUE TITLE
Customize Graph Color in Thermals Chart

### ISSUE THREAD

**Issue by fblix** [fluidd-core/fluidd#994] opened 2022-12-26 20:36 UTC
### Is your feature request related to a problem? Please describe

Hi,

this request is related to the thermals chart tile.

Currently the individual chart colors seem to be related to the fan type.
I am currently running two fans of type `temperature_fan` one for the MCU and one for the bed fans.
Both are colored green which kind of hinders the readability a bit.
See screenshot below for reference.

![Screenshot 2022-12-26 213348](https://user-images.githubusercontent.com/17405838/209581851-cbe4c969-6088-4cfb-90c4-66cbe40445e0.png)

### Describe the solution you'd like

I would love to be able to customize the chart colors individually per graph, even if the fan type is the same.
Meaning instead of having two green charts I would like to be able to have e.g. a yellow and a pink one.

**Comment by pedrolamas** [comment] 2023-01-03 17:05
Duplicate of #534

**Closed** 2023-01-11 09:48 UTC
Labels: FR - Enhancement
